### ISSUE TITLE
deephaven.ui widgets in iframes open multiple panels

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#1039]
**Description**

When opening a deephaven.ui widget from the iframe/widget link, it opens up two panels unnecessarily.

**Steps to reproduce**

1. Create a widget:
```python
from deephaven.ui
b = ui.button("Hello!")
```
2. Open the iframe/widget link: http://localhost:10000/iframe/widget/?name=b

**Expected results**
2. Widget should appear, no panel tabs because it's just one component.

**Actual results**
2. Widget appears but there are two panel tabs. The one panel tab is empty.

**Additional details and attachments**

![image](https://github.com/user-attachments/assets/271e027d-add3-4b12-abbd-3e8fc8ae5c09)

I believe this is caused by @mattrunyon 's changes for https://github.com/deephaven/deephaven-plugins/pull/1023.
It is not present in the commit prior.

**Versions**

Engine Version: 0.37.0
Web UI Version: 0.99.0
Python Version: 3.12.3
Java Version: 11.0.25
Groovy Version: 3.0.22
Barrage Version: 0.7.2
Browser Name: Chrome 130
User Agent OS: Linux
@deephaven/js-plugin-plotly-express: 0.12.0
@deephaven/js-plugin-ui: 0.23.1

**Comment by mattrunyon** [comment]
Investigated this a bit. It seems to be due to the panels in embed-widget being not closeable (which we did on purpose so  you can't get into unrecoverable states).

We could make panels closeable (would be needed if you had conditional rendering of panels anyway). Should also figure out why embed-widget is not re-using the panel like code-studio appears to be.
