### ISSUE TITLE
Queue state updates to trigger re-render after current update cycle

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#116]
This is consistent with the React model.

**Comment by niloc132** [comment]
Two observations:
 * Calling more than one use_state setter callback from an event handler lambda appears to cause the component to re-render twice (arguably the first re-render is while in an inconsistent state, at least relative to how this would work in JS?)
 * Calling a use_state setter with the value it already has currently causes a re-render (which I am presently abusing), but perhaps should instead of a no-op.

**Comment by mofojed** [comment]
A sample snippet to test this out. Create a component with two state variables that should be kept in lock step. Print in each render loop. We should only see one line printed for each press of the button, and a and b should always be equal. Currently we see two lines of output for each button press.
```
import deephaven.ui as ui
from deephaven.ui import use_state


@ui.component
def foo():
    a, set_a = use_state(0)
    b, set_b = use_state(0)

    print(f"Render with a {a} and b {b}")

    def handle_press():
        set_a(a + 1)
        set_b(b + 1)

    return ui.action_button(
        f"a is {a} and b is {b}", on_press=handle_press
    )


f = foo()

```
