### ISSUE TITLE
Plotly express plotby combined with an array for y gives incorrect plot

### ISSUE THREAD

**Issue by mattrunyon** [deephaven/deephaven-plugins#209]
**Description**

Combining the `by` parameter with an array for `y` gives incorrect plots.

**Steps to reproduce**

This code creates `p1` which is incorrect and `p2` which is mostly correct (not sure how the legend should work and yaxis label looks wrong)

```py
from deephaven import empty_table
import deephaven.plot.express as dx

t = empty_table(100).update(["X=ii", "EvenOdd = X % 2", "Ylow=X*EvenOdd-10", "Yhigh=X*EvenOdd+10"])
p1 = dx.line(t, x="X", y=["Ylow", "Yhigh"], by=["EvenOdd"])
p2 = dx.layer(dx.line(t, x="X", y="Ylow", by="EvenOdd"), dx.line(t, x="X", y="Yhigh", by="EvenOdd"))
```

**Expected results**

Mostly this. Although I think the y axis label and legend are probably incorrect.

![image](https://github.com/deephaven/deephaven-plugins/assets/8619789/d9b69100-d550-4b9a-a1be-54b701ea1ae2)

**Actual results**

![image](https://github.com/deephaven/deephaven-plugins/assets/8619789/4306b165-623b-4084-b5b6-cd32cf145131)

**Comment by jnumainville** [comment]
This is expected behavior based on plotly express, although understandably confusing, and will need careful clarification in the docs
`by` in this case acts as the `color` arg in plotly express
plotly express, when provided with a categorical `color` column and a list of columns in `y`, will combine the `y` columns into a another column, `variable`
here is an example of this in action
```
import plotly.express as px
df = px.data.tips()
fig = px.scatter(df, x="total_bill", y=["tip", "size"], color="smoker",
                 title="String 'smoker' values mean discrete colors")

fig.show()
```
<img width="1573" alt="Screenshot 2024-01-18 at 11 56 26 AM" src="https://github.com/deephaven/deephaven-plugins/assets/10480451/1adbee6f-0265-4a6d-a7ea-e179e889b317">

the `tip` and `size` columns are combined into one column that is styled

as for how this can be fixed, `variable` can be used as a `by` column
```
from deephaven import empty_table
import deephaven.plot.express as dx

t = empty_table(100).update(["X=ii", "EvenOdd = X % 2", "Ylow=X*EvenOdd-10", "Yhigh=X*EvenOdd+10"])
p1 = dx.line(t, x="X", y=["Ylow", "Yhigh"], by=["EvenOdd", "variable"])
```
<img width="780" alt="Screenshot 2024-01-18 at 12 00 29 PM" src="https://github.com/deephaven/deephaven-plugins/assets/10480451/c3144acb-0479-45e5-8214-4c7100e4cdf2">

**Comment by vbabich** [comment]
This should be covered by docs, closing.
