### ISSUE TITLE
Open a dashboard in Enterprise

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#264]
Need to be able to open a Dashboard from 1) Code Studio, and 2) From a PQ

Code Studio https://deephaven.atlassian.net/browse/DH-16626
PQ https://deephaven.atlassian.net/browse/DH-16720

**Comment by mofojed** [comment]
Waiting on DH-16249

**Comment by mattrunyon** [comment]
1. Opening from code studio should behave like tables in a code studio. Re-running the code replaces the dashboard if the name doesn't change. Dashboards close w/ "Close Panels on Disconnect" setting
2. Dashboards in a PQ show up in the dashboard list automatically
3. Do not show the dashboard in the PQ panels list. It should be part of the dashboards list.

For code studio dh.ui dashboards, we could consider a tab grouping behavior since the dashboard is tied to the code studio and ephemeral in nature. Once the worker is stopped, the dashboard is no longer retrievable

![Image](https://github.com/deephaven/deephaven-plugins/assets/8619789/bb115e1b-fdf9-4b25-9277-62014a7d1306)

For PQ dashboards, assign the owner as the PQ owner and consider auto-sharing the dashboard with users who have PQ view permission

**Comment by mattrunyon** [comment]
Both enterprise tickets have merged. We should track further improvements in enterprise
