### ISSUE TITLE
Contents of tab panels don't grow/shrink as expected

### ISSUE THREAD

**Issue by dsmmcken** [deephaven/deephaven-plugins#360]
```py
import deephaven.plot.express as dx
import deephaven.ui as ui
from deephaven import empty_table

tabs = ui.view(
    ui.tabs(
        ui.tab_list(ui.item("My Tab", key="tab1")),
        ui.tab_panels(
            ui.item(dx.scatter(empty_table(10).update(["X = i", "Y = i"]), x="X", y="Y"), key="tab1"),
        ),
    ),
    margin="size-100"
)
```

Actual:
Plot doesn't fill the space vertically, and doesn't shrink vertically when the tab is made smaller.

Expected:
Contents of tab panel grows to fill the space vertically and also shrink. 

![image](https://github.com/deephaven/deephaven-plugins/assets/1576283/6ff32d8c-6f0c-4508-acb2-866c97e8b249)

**Comment by AkshatJawne** [comment]
Will be handled in refactored implementation: https://github.com/deephaven/deephaven-plugins/pull/489

**Comment by mattrunyon** [comment]
I don't think this is an issue specifically with tabs, but with the combination of view, tabs, and chart.

`ui.view` adds a div wrapper which uses `display: block`.
`ui.tabs` is a flex container and does not have height/grow set on it
`Chart` seems to be getting the intrinsic height of the entire panel on its first render, setting that, and then it never updates again because the wrapper bounding it has `height: 100%` and that is inside a flex container w/ no height or other children. So that `height: 100%` is `0px`.

There is also no overflow suppression or showing at the panel level. This is a separate issue, but likely needs to be added on `.dh-react-panel`

To fix the above code, you need to add `height="100%"` to both the view and tabs components so that they take up the full space. Or `flex_grow=1` to the view and `height=100%` to the tabs. Since the view is not a flex container, the tabs component cannot use `flex_grow`.

Another potential issue here is the chart seems to have some default size that is not 0x0 (like grid). If you replace the plot w/ a table in the provided code, you get a 0 height table instead. Needs the same fix for sizing the containers to make the table grow.
