### ISSUE TITLE
Release process publishing dev0 build of previous plugin changed

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#387]
**Description**

There's an issue with doing the post-version bump on JS. See this plotly-express action, which published both plotly-express and ui: https://github.com/deephaven/deephaven-plugins/actions/runs/8347726428/job/22848003437
This is because ui had the post version bump, but it was never published; we have no intent of publishing that package post-version bump. Should either _not_ post-version bump JS, or ignore the dev0 builds of JS when publishing.

**Comment by mattrunyon** [comment]
Adding that this is because for JS we use lerna which auto detects what to publish. We could instead tell lerna to only publish the plugin referenced in the version tag instead of detecting which have changed. I still don't know if we really need the dev0 for JS though. Lerna has prerelease flags which NPM auto increments
