### ISSUE TITLE
Discussion about item data source (for list_view, picker, etc)

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#399]
In the [`ui.picker` spec](https://github.com/deephaven/deephaven-plugins/blob/main/plugins/ui/DESIGN.md#uipicker):
```python
ui.picker(
    *children: PickerItem | SectionElement | Table | PartitionedTable,
    key_column: ColumnName | None = None,
    label_column: ColumnName | None = None,
    description_column: ColumnName | None = None,
    icon_column: ColumnName | None = None,
    title_column: ColumnName | None = None,
    ...
```

Similarly, in [`ui.list_view` spec](https://github.com/deephaven/deephaven-plugins/blob/main/plugins/ui/DESIGN.md#uilist_view):
```python
ui.list_view(
    *children: ListViewItem | Table,
    key_column: ColumnName | None = None,
    label_column: ColumnName | None = None,
    description_column: ColumnName | None = None,
    icon_column: ColumnName | None = None,
```

All of those `*_column` arguments are only valid when the children passed in is a `Table` (or `PartitionedTable`) type.

What if we define a `item_table_source` that can be used in either, e.g.:
```python
class ItemDataSource(TypedDict):
  table: Table | PartitionedTable
  key_column: ColumnName | None
  label_column: ColumnName | None
  description_column: ColumnName | None
  icon_column: ColumnName | None
  title_column: ColumnName | None
  actions: ListActionGroupElement | ListActionMenuElement | None

item_table_source(
  table: | Table | PartitionedTable,
  key_column: ColumnName | None = None,
  label_column: ColumnName | None = None,
  description_column: ColumnName | None = None,
  icon_column: ColumnName | None = None,
  title_column: ColumnName | None = None,
) -> ItemDataSource

ui.picker(
    *children: PickerItem | SectionElement | ItemDataSource,
)

ui.list_view(
    *children: PickerItem | SectionElement | ItemDataSource,
)
```

That way the args are only available when using a table as a data source.

**Comment by bmingles** [comment]
I like the `item_table_source` design. Only thing I'm on the fence about is whether this is the only supported way to provide the table data or if we should still support the original pattern as well.

**Comment by jnumainville** [comment]
I think we should still allow `Table` and `PartitionedTable` as they provide a really low friction path.

**Comment by bmingles** [comment]
Another topic to throw in here is the `actions` prop. It currently is specified as `ListActionGroupElement | ListActionMenuElement | None`. The limitation here is that there is no way to dynamically render actions. Scenarios such as disabling or hiding an action that shouldn't be available for a particular item would not be possible since the `ListActionGroupElement` or `ListActionMenuElement` have no access to the item when rendering. We may want to consider actions taking a render function instead of an element. We could then pass the item to the render function so that it could do whatever it wanted based on the data.
